/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class MILK_SUBMIT extends javax.swing.JFrame {
    public Connection conn=null;
    
    
    public Connection getConn(){
        
        try {
            Class.forName("org.postgresql.Driver");
            
        } catch (ClassNotFoundException ex) {
           
            Logger.getLogger(MILK_SUBMIT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      try {
        String url="jdbc:postgresql://localhost/postgres";
        String user="postgres";
        String password="shubhampwr";
        
        
            conn=DriverManager.getConnection(url, user, password);
            //JOptionPane.showMessageDialog(null,"connect");
        } catch (SQLException ex) {
            Logger.getLogger(MILK_SUBMIT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return conn;
        
    }
    
    public void acc()
    {
       int day = 0;
       int month = 0;
       int year=0;
       int abc=0;
       int pqr=0;
       
       try{
        int sf=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO SETUP DATE");
        if(sf==JOptionPane.YES_OPTION)
        {
           String ab=JOptionPane.showInputDialog("Enter Day",day);
           String ac=JOptionPane.showInputDialog("Enter Month",month);
           String ad=JOptionPane.showInputDialog("Enter year",year);
            String date=("DATE :"+ab+"."+ac+"."+ad);
            ab1.setText(date);
            JOptionPane.showMessageDialog(rootPane, date);
            
            String cow=JOptionPane.showInputDialog("Enter Cow Milk Rate",abc);
            String buf=JOptionPane.showInputDialog("Enter BuFf MILK RATE",pqr);
            String rate=("COW :"+cow+"BUFF :"+buf);
            l33.setText(rate);
            t1.setText(cow);
            t2.setText(buf);
        } else {
            if(sf==JOptionPane.NO_OPTION)
                JOptionPane.showMessageDialog(null,"You Dont Set Up Date");
            
        }
        
        
       }catch(Exception e)
       {
           
       }
        
    }
   

    /**
     * Creates new form MILK_SUBMIT
     */
    public MILK_SUBMIT() {
        initComponents();
        getConn();
        acc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        l1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        t8 = new javax.swing.JTextField();
        ab1 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("milk submit");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(100, 100, 1000, 700));
        setMinimumSize(new java.awt.Dimension(687, 424));
        setPreferredSize(new java.awt.Dimension(687, 424));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 70, 100, 0);

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(440, 80, 170, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("USER-ID  :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 80, 80, 17);
        getContentPane().add(t4);
        t4.setBounds(440, 120, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("FAT         :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 120, 80, 20);
        getContentPane().add(t5);
        t5.setBounds(440, 160, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("LITER     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 160, 70, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("CATTEL   :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 200, 70, 20);

        jButton1.setBackground(new java.awt.Color(153, 255, 0));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(50, 199, 10));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 280, 110, 30);

        rb1.setText("cow");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(440, 200, 50, 23);

        rb2.setText("buffelow");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(540, 200, 70, 23);

        l1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l1.setText("TOTEL RS :");
        getContentPane().add(l1);
        l1.setBounds(310, 230, 100, 30);

        jButton4.setBackground(new java.awt.Color(153, 255, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(50, 199, 10));
        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 320, 90, 30);

        jButton3.setBackground(new java.awt.Color(153, 255, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(50, 199, 10));
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 280, 100, 30);
        getContentPane().add(t8);
        t8.setBounds(440, 230, 170, 30);

        ab1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ab1.setForeground(new java.awt.Color(255, 0, 0));
        ab1.setText("DATE :");
        getContentPane().add(ab1);
        ab1.setBounds(20, 20, 220, 30);

        l33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l33.setForeground(new java.awt.Color(255, 0, 0));
        l33.setText("RATE");
        getContentPane().add(l33);
        l33.setBounds(20, 90, 60, 30);

        b1.setText("SET");
        b1.setToolTipText("Update Here Rate");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(60, 210, 130, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("COW   :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 130, 50, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("BUFF    :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 50, 40);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(130, 120, 70, 30);
        getContentPane().add(t2);
        t2.setBounds(130, 160, 70, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/222.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -40, 700, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
      
        
        
        int id =Integer.parseInt(t3.getText());
          int fat =Integer.parseInt(t4.getText());
                  

        
          
              String s1=t1.getText();
              String s2=t2.getText();
              String s3=t5.getText();
               int k  =Integer.parseInt(s1);
                 int p =Integer.parseInt(s2);
                 int w =Integer.parseInt(s3);
                 int total1=0;
           if(rb1.isSelected())
           {
              
              total1=k*p;
             String result=String.valueOf(total1);
             
             t8.setText(result);
             //tf1.setText(result);
            
          }else
           {
               
                total1=k*w;
             String result=String.valueOf(total1);
             
             l1.setText("Total RS="+result);
             
           }
            
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new JFrame3().setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            String query="INSERT INTO public.\"Milk_Submit\"(\n" +
"	\"USER_ID\", \"FAT\", \"LITER\", \"Rupees\")\n" +
"	VALUES (?, ?, ?, ?);";
        PreparedStatement pst;
            pst = conn.prepareStatement(query);
             pst.setInt(1,Integer.valueOf(t3.getText()));
             pst.setInt(2,Integer.valueOf(t4.getText()));
             pst.setInt(3,Integer.valueOf(t5.getText()));
             pst.setInt(4,Integer.valueOf(t8.getText()));
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,t5.getText()+"\t Liter Milk submitted by \n seller :"+t2.getText()+"\n for Rupees :"+t8.getText());
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t8.setText("");
        
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null,"Record not Inserted"+ex);
            
            Logger.getLogger(MILK_SUBMIT.class.getName()).log(Level.SEVERE, null, ex);
        }        
       
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
           int abc=0;
           int pqr=0;
           
        String cow=JOptionPane.showInputDialog("Enter Cow Milk Rate",abc);
            
            String buf=JOptionPane.showInputDialog("Enter BuFf MILK RATE",pqr);
            String rate=("COW :"+cow+"_4"+"BUFF :"+buf);
            l33.setText(rate);
                // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MILK_SUBMIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MILK_SUBMIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MILK_SUBMIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MILK_SUBMIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MILK_SUBMIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ab1;
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l33;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
