
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author LENOVO
 */
public class Milk_Sell extends javax.swing.JFrame {

    public Connection conn=null;
    public ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    public Connection getConn(){
        
        try {
            Class.forName("org.postgresql.Driver");
            
        } catch (ClassNotFoundException ex) {
           
            Logger.getLogger(MILK_SUBMIT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      try {
        String url="jdbc:postgresql://localhost/postgres";
        String user="postgres";
        String password="shubhampwr";
        
        
            conn=DriverManager.getConnection(url, user, password);
            
            //JOptionPane.showMessageDialog(null,"connect");
        } catch (SQLException ex) {
            Logger.getLogger(MILK_SUBMIT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return conn;
        
    }
    
    public void fetch()
    {
        try
        {
           
        String q="SELECT \"Date\", \"C_No\", \"Liter\", \"Rate\", \"Rupees\"\n" +
"	FROM public.\"Milk_Sell\";";
        pst=conn.prepareStatement(q);
        rs=pst.executeQuery();
        
        jtb1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);};
    }
    /**
     * Creates new form Milk_Sell
     */
    public Milk_Sell() {
        initComponents();
        getConn();
        fetch();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<String>();
        cb2 = new javax.swing.JComboBox<String>();
        cb3 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        t31 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setText("SELL MILK :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 180, 34);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Coustmer id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 100, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Milk Liter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 90, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Rate");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 80, 20);

        t1.setToolTipText("Enter Customer ID number");
        getContentPane().add(t1);
        t1.setBounds(130, 120, 90, 30);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(130, 160, 90, 30);

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(130, 200, 90, 30);

        l1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l1.setText("Rupees");
        getContentPane().add(l1);
        l1.setBounds(50, 250, 50, 20);

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SELL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 300, 90, 30);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 300, 90, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 80, 60, 20);

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(70, 80, 50, 20);

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cb2);
        cb2.setBounds(130, 80, 60, 20);

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020" }));
        getContentPane().add(cb3);
        cb3.setBounds(200, 80, 70, 20);

        jtb1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "C_id", "Milk", "Rate", "Rupees"
            }
        ));
        jtb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 100, 400, 180);

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 340, 100, 30);
        getContentPane().add(t31);
        t31.setBounds(130, 240, 90, 30);

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 300, 73, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/img11.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 770, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    try{
        String day=cb1.getItemAt(cb1.getSelectedIndex()); 
        String month=cb2.getItemAt(cb2.getSelectedIndex());
        String year=cb3.getItemAt(cb3.getSelectedIndex());
        String date=(day+"."+month+"."+year);
 
    String a=t1.getText();
    String b=t2.getText();
    String c=t3.getText();
    int rs=0;
    int a1 =Integer.valueOf(b);
    int a2 =Integer.valueOf(c);
    
    rs=a1*a2;
    String Rs=String.valueOf(rs);
             
             t31.setText(Rs);
    
             DefaultTableModel model= (DefaultTableModel) jtb1.getModel();
             model.addRow(new Object[]{date,a,b,c,rs});
             
    
    
    int cno=Integer.parseInt(a);
    Double liter=Double.parseDouble(b);
    Double rate=Double.parseDouble(c);
    Double rs1=Double.parseDouble(Rs);
    
    PreparedStatement pst;
    String sql="INSERT INTO public.\"Milk_Sell\"(\n" +
"	\"Date\", \"C_No\", \"Liter\", \"Rate\", \"Rupees\")\n" +
"	VALUES (?, ?, ?, ?, ?);";
    pst=conn.prepareStatement(sql);
    pst.setInt(2,cno);
    pst.setString(1,date);
    pst.setDouble(3,liter);
    pst.setDouble(4,rate);
    pst.setDouble(5,rs1);
    
    pst.executeUpdate();
    
    JOptionPane.showMessageDialog(null,t2.getText()+"\t Liter  milk sell for \n Customer = "+t1.getText()+"\n for Rupees =\t"+t31.getText());
    t1.setText("");
    t2.setText("");
    l1.setText("Total RS");
    
    
    


    }catch(Exception ev)   
    {
        JOptionPane.showMessageDialog(null, ev);
    };
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
new JFrame3().setVisible(true);  this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try
            {
                String day=cb1.getItemAt(cb1.getSelectedIndex()); 
                String month=cb2.getItemAt(cb2.getSelectedIndex());
                String year=cb3.getItemAt(cb3.getSelectedIndex());
                String date=(day+"."+month+"."+year);
 
    String a=t1.getText();
    String b=t2.getText();
    String c=t3.getText();
    int rs=0;
    int a1 =Integer.valueOf(b);
    int a2 =Integer.valueOf(c);
    
        rs=a1*a2;
        
    String Rs=String.valueOf(rs);
    l1.setText("Total RS="+Rs);
    String sql="UPDATE public.\"Milk_Sell\"\n" +
"	SET \"Date\"='"+date+"', \"C_No\"='"+a+"', \"Liter\"='"+b+"', \"Rate\"='"+c+"', \"Rupees\"='"+Rs+"'\n" +
"	WHERE \"C_No\"='"+a+"' ;";
    
     
               pst=conn.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Record Updated");
            }catch(Exception e){JOptionPane.showMessageDialog(null, e);};




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb1MouseClicked
        // TODO add your handling code here:
        int i=jtb1.getSelectedRow();
        TableModel model=jtb1.getModel();
        t1.setText(model.getValueAt(i, 1).toString());
        t2.setText(model.getValueAt(i, 2).toString());
        t3.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jtb1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

 String a=t1.getText();
    String b=t2.getText();
    String c=t3.getText();
    int rs=0;
    int a1 =Integer.valueOf(b);
    int a2 =Integer.valueOf(c);
    
    rs=a1*a2;
    String Rs=String.valueOf(rs);
             
             t31.setText(Rs);

           // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Milk_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Milk_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Milk_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Milk_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Milk_Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb1;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t31;
    // End of variables declaration//GEN-END:variables
}
